services:
  # Base de Datos MariaDB
  db:
    image: mariadb:10.11
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: martin
      MYSQL_USER: martin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s
    
  # API Laravel
  api:
    build:
      context: ./api-laravel
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: martin
      DB_USERNAME: martin
      DB_PASSWORD: root
    
  # Frontend React
  front:
    build:
      context: ./front-react
      dockerfile: Dockerfile
    container_name: react_front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - api
    volumes:
      - ./front-react:/app
      - /app/node_modules

volumes:
  db_data: